baseurl: "http://blog.bramp.net"
languageCode: "en-gb"
title: "bramp.net"

theme: "bramp"
author:
  name: "Andrew Brampton"

params:
  github: "bramp"
  twitter: "TheBramp"
  linkedin: "bramp"
  facebook: "bramp"
  GoogleAnalytics: "UA-136478-5"
  disqusShortname: "bramp"
  GoogleSiteVerification: "RXqIC-7spNUYReoHFlubz8Fbqsg1fC1pE6FSgSnCNjQ"

permalinks:
  post: /post/:year/:month/:day/:slug/
  publication: /publication/:slug/

taxonomies:
  tag: "tags"
  category: "categories"
  post: "posts"

pygmentscodefences: true
pygmentsuseclasses: true
pygmentsstyle: monokai
pygmentsoptions: startinline=true
