baseurl: "https://bramp.github.io"
altbaseurl: "https://bramp.github.io"
languageCode: "en-gb"
title: "bramp.net"
disqusShortname: "bramp"

theme: "bramp"
author:
  name: "Andrew Brampton"

params:
  github: "bramp"
  twitter: "TheBramp"
  linkedin: "bramp"
  facebook: "bramp"
  GoogleAnalytics: "UA-136478-5"

permalinks:
  posts: /post/:year/:month/:day/:slug/
  publications: /publication/:slug/

taxonomies:
  tag: "tags"
  category: "categories"
  post: "posts"

pygmentscodefences: true
pygmentsuseclasses: true
pygmentsstyle: monokai
pygmentsoptions: startinline=true