baseurl: "https://blog.bramp.net"
languageCode: "en_GB"
title: "bramp.net"

MetaDataFormat: "yaml"

theme: "bramp"
author:
  name: "Andrew Brampton"

# Disabled because it didn't provide a lot of value, and was SLOW.
#DisqusShortname: "bramp"

GoogleAnalytics: "UA-136478-5"

params:
  Description: "Andrew Brampton's Tech blog"
  github: "bramp"
  twitter: "TheBramp"
  linkedin: "bramp"
  facebook: "bramp"
  GoogleSiteVerification: "RXqIC-7spNUYReoHFlubz8Fbqsg1fC1pE6FSgSnCNjQ"
  FeedBurner: "brampnet"
  AddThis: false # Disable the use of the AddThis plugin

permalinks:
  post: /post/:year/:month/:day/:slug/
  publication: /publication/:slug/

taxonomies:
  tag: "tags"
  category: "categories"
  post: "posts"

# TODO Hugo moved to Chroma, does the following work?
pygmentsUseClasses: true
pygmentsStyle: friendly

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true # Allow inline HTML in the markdown