baseurl: "https://blog.bramp.net"
languageCode: "en_GB"
title: "bramp.net"

MetaDataFormat: "yaml"

theme: "bramp"
author:
  name: "Andrew Brampton"

DisqusShortname: "bramp"
GoogleAnalytics: "UA-136478-5"

params:
  Description: "Andrew Brampton's Tech blog"
  github: "bramp"
  twitter: "TheBramp"
  linkedin: "bramp"
  facebook: "bramp"
  GoogleSiteVerification: "RXqIC-7spNUYReoHFlubz8Fbqsg1fC1pE6FSgSnCNjQ"
  FeedBurner: "brampnet"

permalinks:
  post: /post/:year/:month/:day/:slug/
  publication: /publication/:slug/

taxonomies:
  tag: "tags"
  category: "categories"
  post: "posts"

# TODO Hugo moved to Chroma, does the following work?
pygmentsUseClasses: true
pygmentsStyle: friendly
#pygmentsoptions: startinline=true
